#include "DSP/DSPDialect.h"
#include "DSP/DSPOps.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"

// Include the auto-generated implementation of the operations.
// This macro is strictly required by MLIR to instantiate the C++ classes generated by TableGen.
#define GET_OP_CLASSES
#include "DSP/DSPOps.cpp.inc"

using namespace mlir;
using namespace mlir::dsp;

// ------------------------------------------------------------------
// Define the rewrite pattern: SimplifyIDCTofDCT ( IDCT(DCT(x)) = x )
// ------------------------------------------------------------------
struct SimplifyIDCTofDCT : public OpRewritePattern<IDCTOp>
{
    // Inherit from OpRewritePattern and specify IDCTOp as the matching target
    SimplifyIDCTofDCT(MLIRContext *context) : OpRewritePattern<IDCTOp>(context, /*benefit=*/1) 
    {
    }

    // The core logic for pattern matching and graph rewriting
    LogicalResult matchAndRewrite(IDCTOp idctOp, PatternRewriter &rewriter) const override
    {
        // 1. Retrieve the input source value of the IDCT operation
        Value idctInput = idctOp.getInput();

        // 2. Check if this input is produced by a `dsp.dct` operation node.
        DCTOp dctOp = idctInput.getDefiningOp<DCTOp>();

        // 3. If the defining operation cannot be found, or it is not a DCT operation, abort.
        if (!dctOp)
        {
            return failure();
        }

        // 4. Match successful! Replace the output of IDCT with the input of DCT.
        rewriter.replaceOp(idctOp, dctOp.getInput());

        return success();
    }
};

// ------------------------------------------------------------------
// Define the rewrite pattern: SimplifyDCTofIDCT ( DCT(IDCT(x)) = x )
// ------------------------------------------------------------------
struct SimplifyDCTofIDCT : public OpRewritePattern<DCTOp>
{
    // Inherit from OpRewritePattern and specify DCTOp as the matching target
    SimplifyDCTofIDCT(MLIRContext *context) : OpRewritePattern<DCTOp>(context, /*benefit=*/1) 
    {
    }

    // The core logic for pattern matching and graph rewriting
    LogicalResult matchAndRewrite(DCTOp dctOp, PatternRewriter &rewriter) const override
    {
        // 1. Retrieve the input source value of the DCT operation
        Value dctInput = dctOp.getInput();

        // 2. Check if this input is produced by a `dsp.idct` operation node.
        IDCTOp idctOp = dctInput.getDefiningOp<IDCTOp>();

        // 3. If the defining operation cannot be found, or it is not an IDCT operation, abort.
        if (!idctOp)
        {
            return failure();
        }

        // 4. Match successful! Replace the output of DCT with the input of IDCT.
        rewriter.replaceOp(dctOp, idctOp.getInput());

        return success();
    }
};

// ------------------------------------------------------------------
// Register canonicalization patterns into the MLIR system
// ------------------------------------------------------------------

// Instruct MLIR to load these rewrite rules when attempting to optimize IDCTOp
void IDCTOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                         MLIRContext *context)
{
    results.add<SimplifyIDCTofDCT>(context);
}

// Instruct MLIR to load these rewrite rules when attempting to optimize DCTOp
void DCTOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                        MLIRContext *context)
{
    results.add<SimplifyDCTofIDCT>(context);
}